version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  paasdata:
    image: ryesalvador/cmportal_data
    volumes:
      - data-vol:/mysite/media/
    command: tail -f /dev/null
  web:
    image: ryesalvador/cm_portal
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - data-vol:/mysite/media/
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 8000:8000
    depends_on:
      - db
      - paasdata

volumes:
  postgres_data:
  data-vol:
