# Generated by Django 2.0.7 on 2018-07-20 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/employees/%Y/%m/%D')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], max_length=1)),
                ('birth_date', models.DateField()),
                ('permanent_address', models.TextField(max_length=175)),
                ('educational_attainment', models.CharField(blank=True, choices=[('G', 'Elementary Education'), ('H', 'High School'), ('U', 'Undergraduate'), ('C', 'College'), ('P', 'Post Graduate')], max_length=1)),
                ('contact_number', models.CharField(max_length=75)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_security', models.CharField(blank=True, max_length=24)),
                ('philhealth', models.CharField(blank=True, max_length=24)),
                ('pagibig', models.CharField(blank=True, max_length=24)),
                ('tin', models.CharField(blank=True, max_length=24)),
                ('basic_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('allowance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Allowance/De Minimis')),
                ('monthly_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('C', 'Contractual'), ('P', 'Probationary'), ('R', 'Regular'), ('W', 'Resigned'), ('T', 'Terminated')], default='C', max_length=1)),
                ('date_started', models.DateField()),
                ('date_due', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Employee')),
            ],
            options={
                'verbose_name_plural': 'Employment statuses',
                'ordering': ['date_started'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=70)),
                ('evaluation_type', models.CharField(blank=True, max_length=70)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('result', models.CharField(blank=True, choices=[('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('V', 'Very Good'), ('E', 'Excellent')], max_length=1)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cm_portal.Employee')),
            ],
            options={
                'ordering': ['employee'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('specialty', models.CharField(blank=True, max_length=35)),
                ('telephone', models.CharField(max_length=75)),
                ('hospital_of_choice', models.TextField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('job_description', models.TextField(blank=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm_portal.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.TextField(blank=True, max_length=175)),
                ('telephone', models.CharField(blank=True, max_length=75)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm_portal.Relationship')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/residents/%Y/%m/%D')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('osca_id', models.CharField(blank=True, max_length=24)),
                ('address', models.TextField(max_length=175)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=35)),
                ('nationality', models.CharField(max_length=70)),
                ('civil_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], max_length=1)),
                ('most_recent_occupation', models.CharField(blank=True, max_length=70)),
                ('date_and_time_of_admission', models.DateTimeField(blank=True, null=True)),
                ('religion', models.CharField(max_length=70)),
                ('reminders', models.TextField(blank=True)),
                ('advanced_directives', models.CharField(blank=True, max_length=70)),
                ('admitting_diagnosis', models.TextField(blank=True)),
                ('room_number', models.CharField(blank=True, max_length=70)),
                ('diet', models.TextField(blank=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('vital_status', models.CharField(choices=[('LI', 'Living'), ('DE', 'Deceased'), ('DC', 'Discharged')], default='LI', max_length=2)),
                ('died_on', models.DateTimeField(blank=True, null=True)),
                ('discharged_on', models.DateField(blank=True, null=True)),
                ('physicians', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='cm_portal.Physician')),
                ('relatives', sortedm2m.fields.SortedManyToManyField(help_text=None, to='cm_portal.Relative')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cm_portal.Position'),
        ),
    ]
