# Generated by Django 2.0.7 on 2018-07-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='date_and_time_of_admission',
        ),
        migrations.AddField(
            model_name='resident',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='admission_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
