# Generated by Django 2.0.7 on 2018-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0002_auto_20180720_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of admission'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='admission_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time of admission'),
        ),
    ]
