# Generated by Django 2.0.7 on 2018-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0007_auto_20180721_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='died_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
