# Generated by Django 2.0.7 on 2018-08-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0008_auto_20180730_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='relatives',
        ),
        migrations.AlterField(
            model_name='relative',
            name='relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm_portal.Relationship'),
        ),
    ]
