# Generated by Django 2.0.7 on 2018-08-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0009_auto_20180807_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_confinement', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('course_in_the_ward', models.TextField(blank=True)),
                ('resident', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident')),
            ],
            options={
                'ordering': ['resident'],
            },
        ),
    ]
