# Generated by Django 2.0.7 on 2018-08-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0010_medicalabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=35)),
                ('brand_name', models.CharField(blank=True, max_length=35, null=True)),
                ('dosage', models.CharField(blank=True, max_length=35, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=70)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Drug')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident')),
            ],
        ),
    ]
