# Generated by Django 2.0.7 on 2018-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0012_auto_20180907_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['generic_name']},
        ),
        migrations.AlterField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(max_length=70),
        ),
    ]
