# Generated by Django 2.0.7 on 2018-09-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0014_item_iteminstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='perishable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
