# Generated by Django 2.0.7 on 2018-09-24 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0016_resident_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
