# Generated by Django 2.0.7 on 2018-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0017_auto_20180924_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='category_of_care',
            field=models.CharField(blank=True, choices=[('S', 'Skilled Nursing'), ('L', 'Assisted living')], max_length=1),
        ),
    ]
