# Generated by Django 2.0.7 on 2018-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0018_resident_category_of_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
