# Generated by Django 2.0.7 on 2018-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0019_medication_discontinued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='category_of_care',
        ),
        migrations.AddField(
            model_name='resident',
            name='level_of_care',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('I', 'Intermediate'), ('L', 'Low')], max_length=1),
        ),
    ]
