# Generated by Django 2.0.7 on 2018-10-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0020_auto_20181004_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_view_nursing_home', 'View nursing home database'),)},
        ),
    ]
