# Generated by Django 2.0.7 on 2018-10-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0022_auto_20181007_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
    ]
