# Generated by Django 2.0.7 on 2018-10-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0023_auto_20181013_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['item']},
        ),
    ]
