# Generated by Django 2.0.7 on 2018-10-14 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0026_remove_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular medical equipment across whole inventory', primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Medical equipment availability', max_length=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Item')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.RenameModel(
            old_name='ItemInstance',
            new_name='MedicalSupply',
        ),
    ]
