# Generated by Django 2.0.7 on 2018-10-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0027_auto_20181014_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalsupply',
            options={'ordering': ['item'], 'verbose_name_plural': 'Medical supplies'},
        ),
    ]
