# Generated by Django 2.0.7 on 2018-10-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0033_auto_20181014_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalequipment',
            old_name='date_received',
            new_name='date_acquired',
        ),
        migrations.RenameField(
            model_name='medicalsupply',
            old_name='date_received',
            new_name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='perishable',
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
