# Generated by Django 2.0.7 on 2018-10-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0034_auto_20181016_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, choices=[('S', 'Medical Supply'), ('E', 'Medical Equipment')], max_length=1),
        ),
    ]
