# Generated by Django 2.0.7 on 2018-10-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0035_item_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='model',
        ),
    ]
