# Generated by Django 2.0.7 on 2018-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0036_remove_item_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalequipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicalsupply',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
