# Generated by Django 2.0.7 on 2018-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0037_auto_20181021_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
