# Generated by Django 2.0.7 on 2018-10-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0038_auto_20181021_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
