# Generated by Django 2.0.7 on 2018-11-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0039_auto_20181021_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='relationship',
        ),
        migrations.AddField(
            model_name='relative',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident'),
        ),
        migrations.AddField(
            model_name='relative',
            name='relation_to_resident',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
