# Generated by Django 2.0.7 on 2019-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0040_auto_20181129_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('S', 'Medical Supply'), ('E', 'Medical Equipment')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='location',
            field=models.CharField(blank=True, choices=[('R', 'Blessed Enrico Rebuschini Building'), ('L', 'Blessed Luigi Tezza Building'), ('1', 'St. Camillus Building - First floor'), ('2', 'St. Camillus Building - Second floor'), ('3', 'Building 3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='resident',
            name='building',
            field=models.CharField(blank=True, choices=[('R', 'Blessed Enrico Rebuschini Building'), ('L', 'Blessed Luigi Tezza Building'), ('1', 'St. Camillus Building - First floor'), ('2', 'St. Camillus Building - Second floor'), ('3', 'Building 3')], max_length=1),
        ),
    ]
