# Generated by Django 2.0.7 on 2019-01-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0041_auto_20190108_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('resident', models.ForeignKey(limit_choices_to={'vital_status': 'LI'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident')),
            ],
        ),
    ]
