# Generated by Django 2.1.5 on 2019-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='philhealth',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
