# Generated by Django 2.1.5 on 2019-07-11 23:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm_portal', '0003_auto_20190503_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('quantity', models.FloatField()),
                ('unit_of_measure', models.CharField(max_length=35)),
                ('borrower', models.ForeignKey(limit_choices_to={'vital_status': 'LI'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.MedicalSupply')),
            ],
            options={
                'ordering': ['date_acquired'],
            },
        ),
        migrations.AlterField(
            model_name='drug',
            name='indication',
            field=models.TextField(blank=True),
        ),
    ]
