# Generated by Django 2.2.3 on 2019-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0004_auto_20190711_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('alias', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
    ]
