# Generated by Django 2.2.3 on 2019-07-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0005_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
    ]
