# Generated by Django 2.2.3 on 2019-07-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0006_auto_20190720_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Building'),
        ),
    ]
