# Generated by Django 2.2.3 on 2019-07-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0007_resident_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='building',
        ),
    ]
