# Generated by Django 2.2.3 on 2019-08-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0009_auto_20190808_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='related_to',
            field=models.ForeignKey(limit_choices_to={'vital_status': 'LI'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident'),
        ),
    ]
