# Generated by Django 2.2.4 on 2019-08-25 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0010_auto_20190808_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physician',
            old_name='phone_number',
            new_name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='hospital_of_choice',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='specialty',
        ),
        migrations.AddField(
            model_name='physician',
            name='mobile_number_1',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='physician',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='physician',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='physician',
            name='specialties',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_clinic', models.CharField(max_length=70)),
                ('address', models.TextField(max_length=175)),
                ('room', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('clinic_hours', models.TextField(max_length=140)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Physician')),
            ],
        ),
    ]
