# Generated by Django 2.2.4 on 2019-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0011_auto_20190825_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_view_nursing_home', 'View nursing home database'), ('change_resident_diet', "Change resident's DIET ONLY"))},
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=35, verbose_name='name'),
        ),
    ]
