# Generated by Django 2.2.10 on 2020-07-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0012_auto_20191002_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='borrower',
            field=models.ForeignKey(blank=True, limit_choices_to={'vital_status': 'LI'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm_portal.Resident'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='first_name',
            field=models.CharField(max_length=35, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='first_name',
            field=models.CharField(max_length=35, verbose_name='name'),
        ),
    ]
