# Generated by Django 2.2.13 on 2020-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_portal', '0013_auto_20200708_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalequipment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='medicalsupply',
            name='item',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='MedicalEquipment',
        ),
        migrations.DeleteModel(
            name='MedicalSupply',
        ),
    ]
